Impl Zeroize for KeyPair and Certificate
est31/rcgen pull request #48
Opened 2021-01-19 14:45 UTC by didier-wenzek

Here is a proposed implementation for https://github.com/est31/rcgen/issues/47.

This proposition is to have a new optional feature, named `zeroize`. With that option enabled, a dependency to `zeroize` is added and the `Zeroize` trait is implemented for `KeyPair`, and all structures that include such a key pair (`Certificate`, `Certificate`, `CertificateSigningRequest` and `CertificateParams`.

2021-01-19 18:50 UTC, est31 requested changes
Can you please use tabs for indentation? Otherwise looks great.

2021-01-19 21:17 UTC, didier-wenzek commented
Updated using tabs for indentation.

2021-01-19 21:32 UTC, est31 approved these changes
Thanks!

2021-01-19 21:32 UTC, merged

2021-01-20 08:02 UTC, didier-wenzek commented
Thank you!