Implement TryForm<Vec<u8>> for KeyPair struct
est31/rcgen pull request #70
Opened 2022-01-04 14:09 UTC by prx0

Hello!

I've implemented TryForm<Vec<u8>> trait for KeyPair to be able to call try_from on a Vec<u8>, avoid to create a new Vec<u8> from a slice of u8.
I also refactor the logic the get the kind and algorithm used for the serialized DER for TryForm trait.

2022-01-04 21:07 UTC, est31 requested changes
The `TryFrom` impl for the Vec should just call as_slice and then rely on the impl for slices. And I don't like the refactor.

2022-01-04 22:36 UTC, prx0 commented
Do you prefer something like that ? 

```rust
impl TryFrom<&[u8]> for KeyPair {
        type Error = RcgenError;
        fn try_from(pkcs8 :&[u8]) -> Result<KeyPair, RcgenError> {
                // using many if else or just map, as you want
                let (kind, alg) = if let Ok(edkp) = Ed25519KeyPair::from_pkcs8_maybe_unchecked(pkcs8) {
                        (KeyPairKind::Ed(edkp), &PKCS_ED25519)
                } else if let Ok(eckp) = EcdsaKeyPair::from_pkcs8(&signature::ECDSA_P256_SHA256_ASN1_SIGNING, pkcs8) {
                        (KeyPairKind::Ec(eckp), &PKCS_ECDSA_P256_SHA256)
                } else if let Ok(eckp) = EcdsaKeyPair::from_pkcs8(&signature::ECDSA_P384_SHA384_ASN1_SIGNING, pkcs8) {
                        (KeyPairKind::Ec(eckp), &PKCS_ECDSA_P384_SHA384)
                } else if let Ok(rsakp) = RsaKeyPair::from_pkcs8(pkcs8) {
                        (KeyPairKind::Rsa(rsakp, &signature::RSA_PKCS1_SHA256), &PKCS_RSA_SHA256)
                } else {
                        return Err(RcgenError::CouldNotParseKeyPair);
                };

                Ok(KeyPair {
                        kind,
                        alg,
                        serialized_der : pkcs8.to_vec(), // copies the slice into a new vec
                })
        }
}

impl TryFrom<Vec<u8>> for KeyPair {
        type Error = RcgenError;
        fn try_from(pkcs8: Vec<u8>) -> Result<KeyPair, RcgenError> {
            KeyPair::try_from(pkcs8.as_slice())
        }
}
```

But the [to_vec](https://doc.rust-lang.org/nightly/std/primitive.slice.html#method.to_vec) method copies the slice into a new vector in memory. I tried to avoid to create a new vector.

2022-01-04 22:48 UTC, est31 commented
> But the to_vec method copies the slice into a new vector in memory. I tried to avoid to create a new vector.

Oh right good point. Then it should be the slice version that calls the Vec version. All I want it so save on duplicate code :).

2022-01-05 00:23 UTC, Stargateur commented
> > But the to_vec method copies the slice into a new vector in memory. I tried to avoid to create a new vector.
> 
> Oh right good point. Then it should be the slice version that calls the Vec version. All I want it so save on duplicate code :).

Problem is if `slice` version call `Vec<u8>` this will allocate a vector even if the verification fail, it's not duplicate code cause it's have a light behavior difference. The refactor prevent mistake at compile time so it's should be ok.

2022-01-05 00:30 UTC, Stargateur requested changes

2022-01-05 00:30 UTC, Stargateur commented on src/lib.rs
> +        let (kind, alg) = KeyPair::from_raw(pkcs8).expect("unable to detect the kind and algorithm");
`let (kind, alg) = KeyPair::from_raw(pkcs8)?;`

2022-01-05 00:30 UTC, Stargateur commented on src/lib.rs
> +        let (kind, alg) = KeyPair::from_raw(pkcs8.as_slice()).expect("unable to detect kind and algorithm");
`let (kind, alg) = KeyPair::from_raw(pkcs8)?;`

2022-01-05 08:23 UTC, prx0 commented on src/lib.rs
> +        let (kind, alg) = KeyPair::from_raw(pkcs8.as_slice()).expect("unable to detect kind and algorithm");
Thx ! Fixed by https://github.com/est31/rcgen/pull/70/commits/680317503027feccd87e277b1c3f2c2f628ba568

2022-01-05 08:23 UTC, prx0 commented on src/lib.rs
> +        let (kind, alg) = KeyPair::from_raw(pkcs8).expect("unable to detect the kind and algorithm");
Thx ! Fixed by https://github.com/est31/rcgen/pull/70/commits/680317503027feccd87e277b1c3f2c2f628ba568

2022-01-06 02:26 UTC, est31 commented
> Problem is if slice version call Vec<u8> this will allocate a vector even if the verification fail, it's not duplicate code cause it's have a light behavior difference. 

Good point, I think a separate method is good. I still prefer the old if let chain as it is more compact. Also, the PR uses spaces for indentation while this project uses tabs. Would it be possible to adjust to this project's code style?

2022-01-06 08:55 UTC, prx0 commented
> I still prefer the old if let chain as it is more compact. Also, the PR uses spaces for indentation while this project uses tabs. Would it be possible to adjust to this project's code style?

No problem, I changed the code to use tabs instead of spaces and it use the if let chain as you requested.

2022-01-06 11:27 UTC, est31 approved these changes
Thanks!

2022-01-06 11:45 UTC, merged